# Generated by Django 5.1.7 on 2025-03-08 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscriptions",
            old_name="last_checking",
            new_name="last_checkin",
        ),
    ]
