# Generated by Django 5.1.7 on 2025-03-07 19:15

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identity", models.CharField(max_length=20)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="Date"
                    ),
                ),
            ],
            options={"db_table": "projects",},
        ),
        migrations.CreateModel(
            name="Instance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hwid", models.CharField(max_length=50)),
                ("domain", models.CharField(max_length=30)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="myapp.project"
                    ),
                ),
            ],
            options={"db_table": "instances",},
        ),
        migrations.CreateModel(
            name="Subscriptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expires",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="Date"
                    ),
                ),
                ("last_checking", models.DateTimeField(null=True)),
                ("bypass", models.BooleanField(default=False)),
                ("grace_period", models.IntegerField(default=7)),
                (
                    "instance",
                    models.ForeignKey(
                        default=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="myapp.instance",
                    ),
                ),
            ],
        ),
    ]
